name: frailty_graph_viz
channels:
  - defaults
  - condaforge
dependencies:
  - python=3.9
  - networkx
  - ipython
  - uvicorn
  - tqdm
  - fastapi
  - aiofiles
  - spacy
  - pandas
  - ipdb
  - plac
  - sqlalchemy
  - elasticsearch
  - python-dotenv
